name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        config:
        - { os: windows-latest, gen: "Visual Studio 17 2022", gen_short: "vs17_2022", arch: "x64" }
        - { os: ubuntu-latest, gen: "Ninja", gen_short: "ninja", arch: "x86_64" }
    runs-on: ${{ matrix.config.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Deps For Ubuntu
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build cmake zlib1g zlib1g-dev

    - name: Build
      run: |
        cmake -S . -B build -G ${{ matrix.config.gen }} -A ${{ matrix.config.arch }} \
          -DCMAKE_INSTALL_PREFIX=./out/ -DCMAKE_BUILD_TYPE=Release \
          -DPNG_TESTS=OFF -DPNG_SHARED=ON -DPNG_STATIC=ON \
          -DPNG_EXECUTABLES=OFF -DPNG_HARDWARE_OPTIMIZATIONS=ON
        cmake --build build/ --parallel 4
        cmake --install build/ --strip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.os }}-${{ matrix.config.arch }}-${{ matrix.config.gen_short }}
        path: ./out/
        if-no-files-found: error
